version: '3.8'

services:
  my-api:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    ports:
      - "5001:5000"
    deploy:
      replicas: 4

  nginx-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my-api
